import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  ai: [{type: 'autogenerated', dirName: 'ai-coding'}],
  css: [{type: 'autogenerated', dirName: 'css'}],
  html: [{type: 'autogenerated', dirName: 'html'}],
  javascript: [{type: 'autogenerated', dirName: 'javascript'}],
  nodejs: [{type: 'autogenerated', dirName: 'node.js'}],
  react: [{type: 'autogenerated', dirName: 'React'}],
  network: [{type: 'autogenerated', dirName: 'network'}],
  performance: [{type: 'autogenerated', dirName: 'performance'}],
  algorithm: [{type: 'autogenerated', dirName: 'algorithm'}],
  polyfill: [{type: 'autogenerated', dirName: 'polyfill'}],
  scenario: [{type: 'autogenerated', dirName: 'scenario'}],
};

export default sidebars;
